apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: shared
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s/nginx_data  
    server: nas.batcave.local
